name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release

on:
  release:
      types: [created]        

jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-reusable.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://org36dcab52.crm.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://ce-multi-solution-alm-prod.crm.dynamics.com/
      CLIENT_ID: db972f39-0fe5-42f6-a1c6-5f9e1b28be43
      TENANT_ID: 1557f771-4c8e-4dbd-8b80-dd00a88e833e      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
